import Image from "next/image";
import React from "react";

const PatentBio = () => {
  return (
    <div className="p-2 pt-5">
      <div className="flex flex-col md:flex-row justify-between gap-2">
        <div className="flex flex-row justify-between">
          <div>
            <p>Patient Name :</p> <hr />
            <p>Age : </p> <hr />
            <p>Sex : </p> <hr />
            <p>Appointment Date : </p> <hr />
            <p>Generated By :</p>
          </div>
          <div className="text-gray-500">
            <p>Biplob Hossain</p> <hr />
            <p>24 years 5 months 4 days</p>
            <hr />
            <p>Male</p>
            <hr />
            <p>2023-10-23</p>
            <hr />
            <p className="font-bold text-black">PHC Admin</p>
          </div>
        </div>
        <div className="flex  md:flex-row justify-between gap-2">
          <div>
            <p>Arrival Time:</p>
            <hr />
            <p>Community Type : </p>
            <hr />
            <p>Triage Date : </p> <hr />
            <p>Triage Color : </p>
            <hr />
            <p className="">202310220010001</p>
          </div>
          <div className="text-gray-500">
            <p>2023-10-23 01:02:00</p>
            <hr />
            <p>FDMN</p>
            <hr />
            <p>2023-10-23</p>
            <hr />
            <p>Green</p>
            <hr />
            <Image width={50} height={50} src="/icon/qr.png" alt="qr" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default PatentBio;
